export {default as PageHome} from "./page-home";
export {default as PageNewGallery} from "./page-new-gallery";
export {default as PageNewPicture} from "./page-new-picture";
export {default as PageSearch} from "./page-search";
export {default as PageSignIn} from "./page-sign-in";
export {default as PageSignUp} from "./page-sign-up";
export {default as PageUserProfile} from "./page-user-profile";
export {default as PageViewGallery} from "./page-view-gallery";
export {default as PageViewPicture} from "./page-view-picture";